### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-json-schema#11]
@markolson @lihanli I noticed that some of the names of the fields are not consistent with the names HCA uses for the same fields (e.g., for the veteran's name, HCA uses `veteranFullName` and the education schema just uses `fullName`). While the veteran objects are separate now, I think eventually we may move to using a single veteran object for all of vets.gov, so we might as well start making things consistent now. Thoughts?

**Comment by lihanli** [comment]
yea that makes sense, i'll work on changing it
