### ISSUE TITLE
School object in schema

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-json-schema#13]
The `school` object in the schema is structured a little differently than the way the form is asking those questions. `startDate` and `educationObjective` are always available to be filled out. School `name` and `address` only come up when a particular `educationType` is chosen.

The minimal fix is to change `name` from being required. It might also make sense to move `startDate` and `educationObjective` out of the `school` object, since they apply to other education types.

**Comment by jbalboni** [comment]
@lihanli Thoughts?

**Comment by lihanli** [comment]
do you want startDate and educationObjective in the base object like it was before? startDate was also named educationStartDate

**Comment by jbalboni** [comment]
Yeah, I think that fits better. `educationStartDate` sounds good.
