### ISSUE TITLE
Adding YR to Left Nav (IA Recs from Content Team)

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/vets-json-schema#384]
## Acceptance Criteria:
- IA recs from Mikki e.g. related to adding YR to left nav, (Randi likely to implement (bc changes)are required in Drupal)

**Comment by AkucherGCIO** [comment]
@MickinSahni  - not able to add the "vsa-public-websites" label.  Also, which issue are we blocked by ?

**Comment by RLHecht** [comment]
@AkucherGCIO I think you set this ticket up in the wrong repo, which might be why you can't add public websites. Instead of vets-json-schema, you should be in va.gov-team. Let me know if you need help finding it. It should be under Repos in the top left corner of the Zenhub board.

**Comment by AkucherGCIO** [comment]
@RLHecht - Good catch, Randi. I will close this out and create one in the correct repo.
