### ISSUE TITLE
COVID-19 Content: Week of 4.13.20: Restructure FAQs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/vets-json-schema#398]
## User story
As a Veteran, I want to get my top questions about the coronavirus and VA answered as quickly as possible, and have easy access to other questions if I need them.

## Details

Restructure the VA.gov Coronavirus FAQs page as below. Note that we may need to make adjustments to which questions we feature in the top trending questions. I've taken a first pass based on the limited info we have.

1. H1 (no change)
2. Intro (no change)
3. CDC alert (no change)
4. On this page, with updates as below:

Top trending questions from Veterans [alt: Questions Veterans are asking most]
More health care questions
More benefit, claims, and claim exams questions
More debt, copays, and financial questions
More VA national cemeteries and burials questions
Helpful online tools

5. First H2 - change to **Top trending questions from Veterans**

Include the below Q&As in this section, and keep them open (no accordions).

- What should I do if I have symptoms?
- What's VA doing to deal with COVID-19?
- Can I be tested for COVID-19?
- What should I do if I have an upcoming VA health appointment? 
- How do I reschedule or cancel my upcoming VA appointment?
- What should I do if I need to refill my prescription?
- Can I use emergency care?
- Will my benefit payment be delayed because of COVID-19?
- My school changed all classes to online. Will I still qualify for my GI Bill benefits?
- Is VA still doing claim exams (also called compensation and pension, or C&P, exams)?
- What if I had or need an in-person appointment for VA benefits or services?
- What if I can't pay my existing VA debt?

6. Second H2 - change to **More health care questions**

Include the below Q&As in this section as collapsed accordions.

- What's coronavirus COVID-19?
- Can I get a referral to see a community care provider if I can't be seen at VA?
- What should I do if I have a community care appointment?
- What if I tried to call my clinic, and I can't get through?
- What should I do if I need to renew my prescription? _[Note: This is a new question. I will provide content later today]_
- I don't have symptoms, but I feel anxious and overwhelmed. What can I do?
- How do I know if my VA health facility is still open for regular appointments?
- Can I visit a patient at a VA facility?

6. Third H2 - change to **More benefit, claims, and claim exams questions**

Include the below Q&As in this section as collapsed accordions.

- Are VA regional offices closed?
- How can I stay updated on regional office closures or service interruptions?
- How do I contact my local regional office?
- What if I need to turn in paperwork for my claim or appeal?
- What if I need to sign paperwork for my VA claim or other documents?

7. Fourth H2 - change to **More debt, copays, and financial questions**

Include the below Q&As in this section as collapsed accordions.
- Will my COVID-19 stimulus check lower my VA payments?
- What if I’m having trouble paying my VA-backed home loan during this time?
- Will I still have to pay my VA copays during the pandemic?
- What if I’ve been diagnosed with COVID-19 and need immediate action on my VA appeal?
- How do I get help if I'm homeless or at risk of becoming homeless?

8. Fifth H2 - change to **More VA national cemeteries and burials questions**

Include the below Q&As in this section as collapsed accordions.
- Are VA national cemeteries open?
- Can I still schedule a burial at a national cemetery? 
- Can I schedule a committal service or a military funeral honors service?

9. Helpful online tools (no changes)

10. More information (no changes)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. This is the first task for the Coronavirus FAQs updates we need to make today/tomorrow morning. I'd be happy to talk through this before you get started in Drupal. Also, due to my VA network access issues (which I'm hoping to resolve today if I can find the time), I can't move this into In Progress, assign people, add labels. Would you mind doing that and assigning you, me, Jen, Lauren, and Peggy so we can all track the ticket? Thank you so much!

FYI - @jenniferlee-dsva @lalexanderson-dsva @peggygannon

**Comment by jenniferlee-dsva** [comment]
This looks great and I love the rewrite of the top questions label: 
` Questions Veterans are asking most`

What do you think about swapping out the emergency care question with the stimulus check question? 
Swap this: Can I use emergency care?
For this: Will my COVID-19 stimulus check lower my VA payments?

Our call center DOMO unfortunately doesn't provide enough granularity to be helpful, but in SEMRush topic research, VA benefits and VA disability is getting a lot of volume with the topic "stimulus checks veterans."

**Comment by DanielleThierryUSDSVA** [comment]
@jenniferlee-dsva Love the swap of those 2, yes!

@RLHecht, would you mind making that change?

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA These changes were made and new PDF is attached. In the PDF the anchor link for the first H2 isn't working but it's now fixed in Drupal.
[Coronavirus FAQs_ What Veterans Need To Know _ Veterans Affairs 4-14.pdf](https://github.com/department-of-veterans-affairs/vets-json-schema/files/4478538/Coronavirus.FAQs_.What.Veterans.Need.To.Know._.Veterans.Affairs.4-14.pdf)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!

**Comment by jenniferlee-dsva** [comment]
One thing I forgot - from last week: Can we add a link to the direct deposit tool in the Helpful online tools section?  (We held off on that last week, because of the Saturday EVSS scheduled downtime.) 

This page: https://www.va.gov/change-direct-deposit/ 

@RLHecht @DanielleThierryUSDSVA

**Comment by DanielleThierryUSDSVA** [comment]
Adding this doc to capture the additional content changes for this week's faq:

- Addition of approved Annie content
- Proposed MyVA311 messaging
- Revised + new prescription questions
- Direct deposit link added
- Some minor revisions requested by VBA[https://app.zenhub.com/files/66304117/80a09f56-3b5e-4c2e-ad00-3b46e096a7c5/download](https://app.zenhub.com/files/66304117/80a09f56-3b5e-4c2e-ad00-3b46e096a7c5/download)
