### ISSUE TITLE
staging.va.gov:  Past Appointments On the Current Date Not Displaying 

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/vets-json-schema#474]
Steps to recreate
1. In VistA create two appointments (in a clinic configured for VAOS)  on the current date for a patients.  One appt for a time that has passed and one for a time in the future.  
2.  Log in to New UI
3.  Expected Response: In Upcoming Appointments tab the future appt displays.  In Past Appointment tab the past appointment displays.  
4.  Actual Response:  In Upcoming Appointments tab the future appt displays.  In Past Appointment tab the past appointment does **NOT** display.  

This is the patient and these are the appointments current time is as indicated below

APPOINTMENTS FOR: HDRPSIMPATIENTA,JOANN   ***-**-9121 PRINTED: 8/7/2020@14:44

Aug 07, 2020 11:20 AM (60 MINUTES) CHY PC CASSIDY       DOES NOT DISPLAY in Past Appts tab.    In VistA the status of this appointment is   Chy Pc Cassidy            08/07/2020@11:20      No Action Taken/Today and this is an appointment that should display with no status shown.  

Aug 07, 2020  2:20 PM (60 MINUTES) CHY PC CASSIDY        DOES DISPLAY IN Upcoming appts tab.

**Comment by marcynadeau** [comment]
@lenaecb I don't know what I might be doing wrong but I could not add labels or select the template or assign to you.

**Comment by jbalboni** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #12260](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12260) via [**ZenHub**](https://www.zenhub.com/)
