### ISSUE TITLE
Staging:  Direct Scheduling Should be Allowed for Patient in Optometry and Food when VATS is Yes 12 or Yes 24/Optometry Request Should be Allowed

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/vets-json-schema#504]
Scenarios
**Scenario #1 Timeframe 12 mos and #2 TimeFrame 24 mos**
1. In VATS direct scheduling settings for Cheyenne Audiology, Cheyenne Food/Nutrition, Cheyenne Optometry, Sidney Ophthalmology and Cheyenne Move are set to YES, Based on Timeframe 12 mos (same thing happens in Timeframe 24 mos). In VATS requests settings for Cheyenne Audiology, Cheyenne Food/Nutrition, Cheyenne Optometry, Sidney Opthalmology and Cheyenne Move are set to YES, Any Veteran.  
2.  Jacqueline.morgan@id.me has past checked out appts in Optometry and Nutrition in clinics that are not filtered by MAS:  

-  Chy Optometry (IEN 999) 09/07/2020@08:00  Act Req/Checked Out and 

- Chy Nutrition/Satp (IEN 707)       09/07/2020@11:00      Act Req/Checked Out

3.  Select Optometry, VA, Cheyenne.  Expected Response:  Direct Scheduling Flow Displays.  Actual response:  We couldn't find a recent appointment at this location.  
4.  Change type of care to Food/nutrition, VA, Cheyenne.  Expected Response:  Direct Scheduling Flow Displays.  Actual Response: Request flow displays.  

**Scenario#3.  

1.  In VATS Optometry in Cheyenne: Direct Schedule = No.  Requests = Yes
2.    Jacqueline.morgan@id.me.   Select Optometry, VA, Cheyenne.  Expected Response:  Request Flow Displays.  Actual response:  We couldn't find a recent appointment at this location.

**Comment by jbalboni** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #13443](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13443) via [**ZenHub**](https://www.zenhub.com/)
