### ISSUE TITLE
Benefits selection fields

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-json-schema#8]
The benefits selection part of the schema looks like this:

```
    "chapter33": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "electionType": {
          "type": "string"
        },
        "electionDate": {
          "$ref": "#/definitions/date"
        }
      }
    },
    "chapter30": {
      "type": "boolean"
    },
    "chapter1606": {
      "type": "boolean"
    },
    "chapter32": {
      "type": "boolean"
    },
```

In the [wireframes](https://app.moqups.com/greg@adhocteam.us/l32hJ36b/view/page/a9a84ce6e) and in the question doc the way chapter 33 benefits works is slightly different. If you choose chapter33, then you need to pick a benefit to relinquish, which can be chapter 30, chapter 1606, chapter 1607, or "I don't know." The front end model looks like this right now, for example:

```
    "chapter33": true,
    "chapter30": false,
    "chapter1606": true,
    "chapter32": false,
    "benefitsRelinquished": "chapter30" // or chapter1606, chapter1607, or unknown
```
I think the chapter 33 part of the schema is more than we need for the form we're building. What do you think about something more like what the front end model looks like?

**Comment by lihanli** [comment]
i can change it to match the frontend
